package cc.mxtt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenuBtn<M extends BaseMenuBtn<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setMenuId(java.lang.Long menuId) {
		set("menu_id", menuId);
	}

	public java.lang.Long getMenuId() {
		return get("menu_id");
	}

	public void setBtnName(java.lang.String btnName) {
		set("btn_name", btnName);
	}

	public java.lang.String getBtnName() {
		return get("btn_name");
	}

	public void setBtnIcon(java.lang.String btnIcon) {
		set("btn_icon", btnIcon);
	}

	public java.lang.String getBtnIcon() {
		return get("btn_icon");
	}

	public void setBtnMethod(java.lang.String btnMethod) {
		set("btn_method", btnMethod);
	}

	public java.lang.String getBtnMethod() {
		return get("btn_method");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("order_id");
	}

}
