package cc.mxtt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXxDict<M extends BaseXxDict<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setBm(java.lang.String bm) {
		set("bm", bm);
	}

	public java.lang.String getBm() {
		return get("bm");
	}

	public void setMc(java.lang.String mc) {
		set("mc", mc);
	}

	public java.lang.String getMc() {
		return get("mc");
	}

	public void setQybz(java.lang.String qybz) {
		set("qybz", qybz);
	}

	public java.lang.String getQybz() {
		return get("qybz");
	}

	public void setXgbz(java.lang.String xgbz) {
		set("xgbz", xgbz);
	}

	public java.lang.String getXgbz() {
		return get("xgbz");
	}

}
