package com.yunshi.tengma.common.model;

import com.yunshi.tengma.common.model.base.BaseCjDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CjDict extends BaseCjDict<CjDict> {
	public static final CjDict dao = new CjDict();
}
