package com.yunshi.tengma.common.model;

import com.yunshi.tengma.common.model.base.BaseVSysCjDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VSysCjDict extends BaseVSysCjDict<VSysCjDict> {
	public static final VSysCjDict dao = new VSysCjDict();
}
