package com.yunshi.tengma.common.model;

import com.yunshi.tengma.common.model.base.BaseVSysXxDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VSysXxDict extends BaseVSysXxDict<VSysXxDict> {
	public static final VSysXxDict dao = new VSysXxDict();
}
