package com.yunshi.tengma.common.model;

import com.yunshi.tengma.common.model.base.BaseXxDictDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XxDictDetail extends BaseXxDictDetail<XxDictDetail> {
	public static final XxDictDetail dao = new XxDictDetail();
}
