package com.yunshi.tengma.common.model;

import com.yunshi.tengma.common.model.base.BaseXxDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XxDict extends BaseXxDict<XxDict> {
	public static final XxDict dao = new XxDict();
}
