package com.yunshi.tengma.common.model;

import com.yunshi.tengma.common.model.base.BaseZsGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZsGroup extends BaseZsGroup<ZsGroup> {
	public static final ZsGroup dao = new ZsGroup();
}
