package com.yunshi.tengma.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVSysXxDict<M extends BaseVSysXxDict<M>> extends Model<M> implements IBean {

	public void setDLBM(java.lang.String DLBM) {
		set("DLBM", DLBM);
	}

	public java.lang.String getDLBM() {
		return get("DLBM");
	}

	public void setDLMC(java.lang.String DLMC) {
		set("DLMC", DLMC);
	}

	public java.lang.String getDLMC() {
		return get("DLMC");
	}

	public void setBM(java.lang.String BM) {
		set("BM", BM);
	}

	public java.lang.String getBM() {
		return get("BM");
	}

	public void setMC(java.lang.String MC) {
		set("MC", MC);
	}

	public java.lang.String getMC() {
		return get("MC");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("ORDER_ID", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("ORDER_ID");
	}

	public void setQYBZ(java.lang.String QYBZ) {
		set("QYBZ", QYBZ);
	}

	public java.lang.String getQYBZ() {
		return get("QYBZ");
	}

	public void setXGBZ(java.lang.String XGBZ) {
		set("XGBZ", XGBZ);
	}

	public java.lang.String getXGBZ() {
		return get("XGBZ");
	}

}
