package cc.mxtt.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_cj_dict", "id", CjDict.class);
		arp.addMapping("sys_menu_btn", "id", MenuBtn.class);
		arp.addMapping("sys_xx_dict", "id", XxDict.class);
		arp.addMapping("sys_xx_dict_detail", "id", XxDictDetail.class);
		arp.addMapping("zs_content", "id", ZsContent.class);
		arp.addMapping("zs_group", "id", ZsGroup.class);
	}
}

