package cc.mxtt.common.model;

import cc.mxtt.common.model.base.BaseCjDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CjDict extends BaseCjDict<CjDict> {
	public static final CjDict dao = new CjDict();
}
