package cc.mxtt.common.model;

import cc.mxtt.common.model.base.BaseMenuBtn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuBtn extends BaseMenuBtn<MenuBtn> {
	public static final MenuBtn dao = new MenuBtn();
}
