package cc.mxtt.common.model;

import cc.mxtt.common.model.base.BaseVSysXxDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VSysXxDict extends BaseVSysXxDict<VSysXxDict> {
	public static final VSysXxDict dao = new VSysXxDict();
}
