package cc.mxtt.common.model;

import cc.mxtt.common.model.base.BaseVSysCjDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VSysCjDict extends BaseVSysCjDict<VSysCjDict> {
	public static final VSysCjDict dao = new VSysCjDict();
}
