package cc.mxtt.common.model;

import cc.mxtt.common.model.base.BaseXxDictDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XxDictDetail extends BaseXxDictDetail<XxDictDetail> {
	public static final XxDictDetail dao = new XxDictDetail();
}
