package cc.mxtt.common.model;

import cc.mxtt.common.model.base.BaseXxDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XxDict extends BaseXxDict<XxDict> {
	public static final XxDict dao = new XxDict();
}
