package cc.mxtt.common.model;

import cc.mxtt.common.model.base.BaseZsContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZsContent extends BaseZsContent<ZsContent> {
	public static final ZsContent dao = new ZsContent();
}
