package cc.mxtt.common.model;

import cc.mxtt.common.model.base.BaseZsGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZsGroup extends BaseZsGroup<ZsGroup> {
	public static final ZsGroup dao = new ZsGroup();
}
